# Basic
max_width = 100
# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_imports = true
# Comments
comment_width = 100
normalize_comments = true
wrap_comments = true
# Consistency
newline_style = "Unix"